namespace: default
resources:
  - nginx.yaml
  - mariadb.yaml
  - backend.yaml
  - frontend.yaml
  - redis.yaml
  # - node-exporter-daemonset.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
configMapGenerator:
  - name: redis-configmap
    files:
      - configs/redis.conf